language: php

php:
  - "7.1"
  - "7.2"

services: mysql

before_install:
  - mysql -e 'CREATE DATABASE oxid;'

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sh ./.travis.before_script.sh

script:
  - cd ~/OXID/
  - ./vendor/bin/runtests
