
oxidcommunity_moduleinstaller_auth:
    path: /oxid/moduleinstaller/auth/
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:User:auth"

oxidcommunity_moduleinstaller_auth_jwt:
    path: /oxid/moduleinstaller/auth/check/
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:User:jwt"

### PACKAGES

oxidcommunity_moduleinstaller_packages_new:
    path: /oxid/moduleinstaller/packages/
    options:
        auth: true
    methods: [POST]
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:new"

oxidcommunity_moduleinstaller_packages_search:
    path: /oxid/moduleinstaller/packages/{item}/
    methods: [POST]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:search"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_packages_update:
    path: /oxid/moduleinstaller/packages/
    methods: [PUT]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:update"
        
oxidcommunity_moduleinstaller_packages_update_2:
    path: /oxid/moduleinstaller/packages/update/
    methods: [GET]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:update"

oxidcommunity_moduleinstaller_packages_update_selected:
    path: /oxid/moduleinstaller/packages/selected/
    methods: [PUT]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:updateSelected"

oxidcommunity_moduleinstaller_packages_delete:
    path: /oxid/moduleinstaller/packages/
    methods: [DELETE]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:delete"

oxidcommunity_moduleinstaller_packages:
    path: /oxid/moduleinstaller/packages/
    methods: [GET]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Packages:index"



### REPOSITORIES

oxidcommunity_moduleinstaller_repositories_new:
    path: /oxid/moduleinstaller/repositories/
    methods: [POST]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Repositories:new"

oxidcommunity_moduleinstaller_repositories_update:
    path: /oxid/moduleinstaller/repositories/
    methods: [PUT]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Repositories:update"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_repositories_delete:
    path: /oxid/moduleinstaller/repositories/
    methods: [DELETE]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Repositories:delete"

oxidcommunity_moduleinstaller_repositories:
    path: /oxid/moduleinstaller/repositories/
    methods: [GET]
    options:
        auth: true
    defaults:
        _controller: "OxidCommunityModuleInstallerBundle:Repositories:index"


oxidcommunity_moduleinstaller_catchall:
    path: /{_url_fragment}
    defaults:
        _scope: frontend
        _token_check: true
        _controller: "OxidCommunityModuleInstallerBundle:Frontend:index"
    requirements:
        _url_fragment: .*