
### PACKAGES

oxidcommunity_moduleinstaller_packages_new:
    path: /oxid/moduleinstaller/packages/
    methods: [POST]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:new"

oxidcommunity_moduleinstaller_packages_show:
    path: /oxid/moduleinstaller/packages/{item}/
    methods: [GET]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:show"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_packages_update:
    path: /oxid/moduleinstaller/packages/{item}/
    methods: [PUT]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:update"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_packages_delete:
    path: /oxid/moduleinstaller/packages/{item}/
    methods: [DELETE]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:delete"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_packages:
    path: /oxid/moduleinstaller/packages/
    methods: [GET]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:index"



### REPOSITORIES

oxidcommunity_moduleinstaller_repositories_new:
    path: /oxid/moduleinstaller/repositories/
    methods: [POST]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Packages:new"

oxidcommunity_moduleinstaller_repositories_show:
    path: /oxid/moduleinstaller/repositories/{item}/
    methods: [GET]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Repositories:show"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_repositories_update:
    path: /oxid/moduleinstaller/repositories/{item}/
    methods: [PUT]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Repositories:update"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_repositories_delete:
    path: /oxid/moduleinstaller/repositories/{item}/
    methods: [DELETE]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Repositories:delete"
    requirements:
        item: .+

oxidcommunity_moduleinstaller_repositories:
    path: /oxid/moduleinstaller/repositories/
    methods: [GET]
    defaults:
        _controller: "OxidCommunityModuleinstallerBundle:Repositories:index"
